// SWC가 CommonJS로 실행하는 테스트에서 사용하는 ESM 네트워크/Markdown 의존성.
const esmPackages = [
  'ky',
  'until-async',
  'rettime',
  '@open-draft/deferred-promise',
  'react-markdown',
  'remark-[^/]+',
  'rehype-[^/]+',
  'unified',
  'hast-util-[^/]+',
  'mdast-util-[^/]+',
  'micromark(?:-[^/]+)?',
  'unist-util-[^/]+',
  'vfile(?:-[^/]+)?',
  'devlop',
  'comma-separated-tokens',
  'space-separated-tokens',
  'estree-util-is-identifier-name',
  'decode-named-character-reference',
  'character-entities(?:-[^/]+)?',
  'character-reference-invalid',
  'longest-streak',
  'zwitch',
  'ccount',
  'parse-entities',
  'is-alphanumerical',
  'is-alphabetical',
  'is-decimal',
  'is-hexadecimal',
  'stringify-entities',
  'property-information',
  'html-url-attributes',
  'trim-lines',
  'bail',
  'trough',
  'markdown-table',
  'hastscript',
  'web-namespaces',
  'html-void-elements',
  'parse5',
  'entities',
  'is-plain-obj',
  'escape-string-regexp',
];

/** @type {import('jest').Config} */
export default {
  testEnvironment: '<rootDir>/jest.environment.js',
  testEnvironmentOptions: { customExportConditions: ['node', 'node-addons'] },
  // 모달을 열고 검색해 고르는 흐름은 기본 5초로는 빠듯하다.
  testTimeout: 15_000,
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  transform: {
    '^.+\\.(?:[cm]?j|t)sx?$': [
      '@swc/jest',
      {
        swcrc: false,
        jsc: {
          parser: { syntax: 'typescript', tsx: true },
          transform: { react: { runtime: 'automatic' } },
          target: 'es2022',
        },
      },
    ],
  },
  transformIgnorePatterns: [`/node_modules/(?!(${esmPackages.join('|')})/)`],
};
