plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.epages.restdocs-api-spec' version '0.20.1'
}

group = 'com.shoutoutz'
version = '0.0.1-SNAPSHOT'
description = 'Shout-outz API'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    implementation 'org.springframework.boot:spring-boot-starter-flyway'
    implementation 'org.flywaydb:flyway-database-postgresql'

    runtimeOnly 'org.postgresql:postgresql'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-restdocs'
    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
    testImplementation 'com.epages:restdocs-api-spec-mockmvc:0.20.1' //OAS로 변경 해주는 라이브러리. restassured가 아닌 mockmvc를 기반으로 한다.
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.add('-parameters')
    options.encoding = 'UTF-8'
}

tasks.named('test') {
    useJUnitPlatform()
}

openapi3 {
    server = 'http://localhost:8080'
    title = 'Shout-outz API'
    description = 'Shout-outz Backend API'
    version = project.version
    format = 'yaml'
}

/**
 * OpenAPI yaml 파일(OAS 스펙)을 Swagger UI가 읽을 수 있도록 정적 리소스 위치로 복사
 */
tasks.register('copyOasToSwagger', Copy) {
    dependsOn tasks.named('openapi3')

    from(layout.buildDirectory.file('api-spec/openapi3.yaml'))
    into(layout.projectDirectory.dir('src/main/resources/static/docs'))
}
