CREATE TABLE bug_reports (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content                  TEXT NOT NULL,
    reporter_user_id         BIGINT REFERENCES users (id) ON DELETE SET NULL,
    status                   VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    status_changed_at        TIMESTAMPTZ,
    status_changed_by_user_id BIGINT REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT bug_reports_status_check CHECK (status IN ('OPEN', 'COMPLETED')),
    CONSTRAINT bug_reports_content_length_check CHECK (char_length(content) BETWEEN 1 AND 5000)
);

CREATE INDEX bug_reports_status_created_at_id_idx
    ON bug_reports (status, created_at DESC, id DESC);

CREATE INDEX bug_reports_created_at_id_idx
    ON bug_reports (created_at DESC, id DESC);
