/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as CommunityFeedIdRouteImport } from './routes/community/$feedId'
import { Route as CommunityNewRouteImport } from './routes/community/new'
import { Route as FeedsIndexRouteImport } from './routes/feeds/index'
import { Route as FeedsFeedIdRouteImport } from './routes/feeds/$feedId'
import { Route as FeedsNewRouteImport } from './routes/feeds/new'
import { Route as MypageVerificationRouteImport } from './routes/mypage/verification'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsNewsIdRouteImport } from './routes/news/$newsId'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as UsersHandleRouteImport } from './routes/users/$handle'
import { Route as CommunityFeedIdEditRouteImport } from './routes/community/$feedId_.edit'
import { Route as FeedsFeedIdEditRouteImport } from './routes/feeds/$feedId_.edit'
import { Route as ProjectsSlugEditRouteImport } from './routes/projects/$slug_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityFeedIdRoute = CommunityFeedIdRouteImport.update({
  id: '/community/$feedId',
  path: '/community/$feedId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityNewRoute = CommunityNewRouteImport.update({
  id: '/community/new',
  path: '/community/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsIndexRoute = FeedsIndexRouteImport.update({
  id: '/feeds/',
  path: '/feeds/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsFeedIdRoute = FeedsFeedIdRouteImport.update({
  id: '/feeds/$feedId',
  path: '/feeds/$feedId',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsNewRoute = FeedsNewRouteImport.update({
  id: '/feeds/new',
  path: '/feeds/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageVerificationRoute = MypageVerificationRouteImport.update({
  id: '/mypage/verification',
  path: '/mypage/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewsIdRoute = NewsNewsIdRouteImport.update({
  id: '/news/$newsId',
  path: '/news/$newsId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersHandleRoute = UsersHandleRouteImport.update({
  id: '/users/$handle',
  path: '/users/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityFeedIdEditRoute = CommunityFeedIdEditRouteImport.update({
  id: '/community/$feedId_/edit',
  path: '/community/$feedId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsFeedIdEditRoute = FeedsFeedIdEditRouteImport.update({
  id: '/feeds/$feedId_/edit',
  path: '/feeds/$feedId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugEditRoute = ProjectsSlugEditRouteImport.update({
  id: '/projects/$slug_/edit',
  path: '/projects/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/signup': typeof SignupRoute
  '/community/$feedId': typeof CommunityFeedIdRoute
  '/community/new': typeof CommunityNewRoute
  '/feeds/$feedId': typeof FeedsFeedIdRoute
  '/feeds/new': typeof FeedsNewRoute
  '/mypage/verification': typeof MypageVerificationRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/new': typeof ProjectsNewRoute
  '/users/$handle': typeof UsersHandleRoute
  '/community/': typeof CommunityIndexRoute
  '/feeds/': typeof FeedsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/community/$feedId/edit': typeof CommunityFeedIdEditRoute
  '/feeds/$feedId/edit': typeof FeedsFeedIdEditRoute
  '/projects/$slug/edit': typeof ProjectsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/signup': typeof SignupRoute
  '/community/$feedId': typeof CommunityFeedIdRoute
  '/community/new': typeof CommunityNewRoute
  '/feeds/$feedId': typeof FeedsFeedIdRoute
  '/feeds/new': typeof FeedsNewRoute
  '/mypage/verification': typeof MypageVerificationRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/new': typeof ProjectsNewRoute
  '/users/$handle': typeof UsersHandleRoute
  '/community': typeof CommunityIndexRoute
  '/feeds': typeof FeedsIndexRoute
  '/news': typeof NewsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/community/$feedId/edit': typeof CommunityFeedIdEditRoute
  '/feeds/$feedId/edit': typeof FeedsFeedIdEditRoute
  '/projects/$slug/edit': typeof ProjectsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/signup': typeof SignupRoute
  '/community/$feedId': typeof CommunityFeedIdRoute
  '/community/new': typeof CommunityNewRoute
  '/feeds/$feedId': typeof FeedsFeedIdRoute
  '/feeds/new': typeof FeedsNewRoute
  '/mypage/verification': typeof MypageVerificationRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/new': typeof ProjectsNewRoute
  '/users/$handle': typeof UsersHandleRoute
  '/community/': typeof CommunityIndexRoute
  '/feeds/': typeof FeedsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/community/$feedId_/edit': typeof CommunityFeedIdEditRoute
  '/feeds/$feedId_/edit': typeof FeedsFeedIdEditRoute
  '/projects/$slug_/edit': typeof ProjectsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/signup'
    | '/community/$feedId'
    | '/community/new'
    | '/feeds/$feedId'
    | '/feeds/new'
    | '/mypage/verification'
    | '/news/$newsId'
    | '/projects/$slug'
    | '/projects/new'
    | '/users/$handle'
    | '/community/'
    | '/feeds/'
    | '/news/'
    | '/projects/'
    | '/community/$feedId/edit'
    | '/feeds/$feedId/edit'
    | '/projects/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/signup'
    | '/community/$feedId'
    | '/community/new'
    | '/feeds/$feedId'
    | '/feeds/new'
    | '/mypage/verification'
    | '/news/$newsId'
    | '/projects/$slug'
    | '/projects/new'
    | '/users/$handle'
    | '/community'
    | '/feeds'
    | '/news'
    | '/projects'
    | '/community/$feedId/edit'
    | '/feeds/$feedId/edit'
    | '/projects/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/signup'
    | '/community/$feedId'
    | '/community/new'
    | '/feeds/$feedId'
    | '/feeds/new'
    | '/mypage/verification'
    | '/news/$newsId'
    | '/projects/$slug'
    | '/projects/new'
    | '/users/$handle'
    | '/community/'
    | '/feeds/'
    | '/news/'
    | '/projects/'
    | '/community/$feedId_/edit'
    | '/feeds/$feedId_/edit'
    | '/projects/$slug_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  SignupRoute: typeof SignupRoute
  CommunityFeedIdRoute: typeof CommunityFeedIdRoute
  CommunityNewRoute: typeof CommunityNewRoute
  FeedsFeedIdRoute: typeof FeedsFeedIdRoute
  FeedsNewRoute: typeof FeedsNewRoute
  MypageVerificationRoute: typeof MypageVerificationRoute
  NewsNewsIdRoute: typeof NewsNewsIdRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  UsersHandleRoute: typeof UsersHandleRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  FeedsIndexRoute: typeof FeedsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  CommunityFeedIdEditRoute: typeof CommunityFeedIdEditRoute
  FeedsFeedIdEditRoute: typeof FeedsFeedIdEditRoute
  ProjectsSlugEditRoute: typeof ProjectsSlugEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$feedId': {
      id: '/community/$feedId'
      path: '/community/$feedId'
      fullPath: '/community/$feedId'
      preLoaderRoute: typeof CommunityFeedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/new': {
      id: '/community/new'
      path: '/community/new'
      fullPath: '/community/new'
      preLoaderRoute: typeof CommunityNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/': {
      id: '/feeds/'
      path: '/feeds'
      fullPath: '/feeds/'
      preLoaderRoute: typeof FeedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/$feedId': {
      id: '/feeds/$feedId'
      path: '/feeds/$feedId'
      fullPath: '/feeds/$feedId'
      preLoaderRoute: typeof FeedsFeedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/new': {
      id: '/feeds/new'
      path: '/feeds/new'
      fullPath: '/feeds/new'
      preLoaderRoute: typeof FeedsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/verification': {
      id: '/mypage/verification'
      path: '/mypage/verification'
      fullPath: '/mypage/verification'
      preLoaderRoute: typeof MypageVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$newsId': {
      id: '/news/$newsId'
      path: '/news/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof NewsNewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$handle': {
      id: '/users/$handle'
      path: '/users/$handle'
      fullPath: '/users/$handle'
      preLoaderRoute: typeof UsersHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$feedId_/edit': {
      id: '/community/$feedId_/edit'
      path: '/community/$feedId/edit'
      fullPath: '/community/$feedId/edit'
      preLoaderRoute: typeof CommunityFeedIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/$feedId_/edit': {
      id: '/feeds/$feedId_/edit'
      path: '/feeds/$feedId/edit'
      fullPath: '/feeds/$feedId/edit'
      preLoaderRoute: typeof FeedsFeedIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug_/edit': {
      id: '/projects/$slug_/edit'
      path: '/projects/$slug/edit'
      fullPath: '/projects/$slug/edit'
      preLoaderRoute: typeof ProjectsSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  SignupRoute: SignupRoute,
  CommunityFeedIdRoute: CommunityFeedIdRoute,
  CommunityNewRoute: CommunityNewRoute,
  FeedsFeedIdRoute: FeedsFeedIdRoute,
  FeedsNewRoute: FeedsNewRoute,
  MypageVerificationRoute: MypageVerificationRoute,
  NewsNewsIdRoute: NewsNewsIdRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  UsersHandleRoute: UsersHandleRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  FeedsIndexRoute: FeedsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  CommunityFeedIdEditRoute: CommunityFeedIdEditRoute,
  FeedsFeedIdEditRoute: FeedsFeedIdEditRoute,
  ProjectsSlugEditRoute: ProjectsSlugEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
