/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProjectDetailIndexRouteImport } from './routes/project-detail/index'
import { Route as ProjectDetailIdRouteImport } from './routes/project-detail/$id'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectDetailIndexRoute = ProjectDetailIndexRouteImport.update({
  id: '/project-detail/',
  path: '/project-detail/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectDetailIdRoute = ProjectDetailIdRouteImport.update({
  id: '/project-detail/$id',
  path: '/project-detail/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/project-detail/$id': typeof ProjectDetailIdRoute
  '/project-detail/': typeof ProjectDetailIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/project-detail/$id': typeof ProjectDetailIdRoute
  '/project-detail': typeof ProjectDetailIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/project-detail/$id': typeof ProjectDetailIdRoute
  '/project-detail/': typeof ProjectDetailIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/project-detail/$id' | '/project-detail/' | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/project-detail/$id' | '/project-detail' | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/project-detail/$id'
    | '/project-detail/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProjectDetailIdRoute: typeof ProjectDetailIdRoute
  ProjectDetailIndexRoute: typeof ProjectDetailIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-detail/': {
      id: '/project-detail/'
      path: '/project-detail'
      fullPath: '/project-detail/'
      preLoaderRoute: typeof ProjectDetailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-detail/$id': {
      id: '/project-detail/$id'
      path: '/project-detail/$id'
      fullPath: '/project-detail/$id'
      preLoaderRoute: typeof ProjectDetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProjectDetailIdRoute: ProjectDetailIdRoute,
  ProjectDetailIndexRoute: ProjectDetailIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
