spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shoutoutz
    username: shoutoutz
    password: localdev
    driver-class-name: org.postgresql.Driver

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_REGION}
    presigned-url-expiration-seconds: ${AWS_S3_PRESIGNED_URL_EXPIRATION_SECONDS}
